### ISSUE TITLE
Link not getting embedded

### ISSUE THREAD

**Issue by PrashantDixit0** [Aetherinox/mkdocs-link-embeds#4]
Link Embedding is not working 
installed `mkdocs-link-embeds-plugin` and added `link-embeds.css` in `extra_css` section, but still not working

used following snippet
![Screenshot from 2024-09-04 16-27-00](https://github.com/user-attachments/assets/82e49edc-7e8a-49cb-a370-39d7b483c904)
 
but not getting results

![Screenshot from 2024-09-04 16-23-40](https://github.com/user-attachments/assets/dc4bc791-75da-4353-9077-559c65ff253e)

**Comment by Aetherinox** [comment]
If you serve up mkdocs locally on your machine via `mkdocs serve`, are you seeing anything at all in regards to this plugin running?

Latest version has verbose logging, so it's pretty hard to miss in the console

```
VERBOSE -  Loading Page: Page(title='Link Embeds Plugin', url='/')
VERBOSE -  Loading Page: Page(title='Demo', url='/demo/')
VERBOSE -  Loading Page: Page(title='Home', url='/home/')
VERBOSE -  Loading Page: Page(title='Backers', url='/about/backers/')
VERBOSE -  Loading Page: Page(title='Changelog', url='/about/changelog/')
```

It should throw info about each link you have created and the page title that it found the link on.

**Comment by PrashantDixit0** [comment]
No verbose logging is on console

**Comment by PrashantDixit0** [comment]
@Aetherinox What could be the reasons it's not working for me and not even giving console logs

**Comment by Aetherinox** [comment]
Hrm, I just did a fresh install on both my machine, and a test Github workflow.

When you run
```
pip list
```

on the machine you're building docs on, do you see the following in your list?

![tyUEnTvTRW](https://github.com/user-attachments/assets/4b28c251-21af-46a1-8344-13b26e37df28)


And then for my `mkdocs.yml` file, all I have in there is

```yml
plugins:
  - link-embeds:
      enabled: true
      name_default: "Untitled Link"
      desc_default: "No description found"
      image_default: "url.com"
      image_disabled: false
      favicon_default: "url.com"
      favicon_disabled: true
      favicon_size: 25
      target: "blank"
      accent: "FFFFFF1A"
      verbose: true
```

As an added note, currently running:
- pip 24.2 from *site-packages\pip (python 3.12)
